### ISSUE TITLE
limactl does not exist of M1 macOS since latest apple update - it thinks it is infected with a virus

### ISSUE THREAD

**Issue by mmhealey1** [lima-vm/lima#1028]
### Description

See https://github.com/rancher-sandbox/rancher-desktop/issues/2798 for information

**Comment by AkihiroSuda** [comment]
@mmhealey1
What is your virus scanning software?
How is Lima misidentified as a virus?

**Comment by AkihiroSuda** [comment]
Docker for Mac and others seem affected too
- https://github.com/docker/for-mac/issues/6456
- https://github.com/electron-userland/electron-builder/issues/7082

- https://github.com/rancher-sandbox/rancher-desktop/issues/2803
- https://github.com/rancher-sandbox/rancher-desktop/issues/2793
- https://github.com/rancher-sandbox/rancher-desktop/issues/2798

**Comment by AkihiroSuda** [comment]
The false-positive of `Osx.Exploit.CVE_2021_4034-9951522-2` seems to have been fixed in clamav-virusdb 26636 (Aug 23). https://lists.clamav.net/pipermail/clamav-virusdb/2022-August/008021.html
Cisco's product seems using the same DB.

Not sure about XProtect (https://github.com/rancher-sandbox/rancher-desktop/issues/2798#issuecomment-1222221053).

**Comment by AkihiroSuda** [comment]
@mmhealey1 

Is this still an issue? Could you try updating the virus definitions?

**Comment by mmhealey1** [comment]
Updated virus definitions have fixed it .
