### ISSUE TITLE
Move from github.com/AkihiroSuda to github.com/lima-vm

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#119]
`github.com/lima` is already taken by another project, so we have to come up with another name, e.g., `github.com/linuxmachines`.

We can also consider renaming `lima` itself, as there has been also Lima GPU driver project (https://gitlab.freedesktop.org/lima). (But finding an unique/short/rememberable name is not easy 😅 )

 - - -
**EDIT** Created https://github.com/lima-vm . Thanks to @jandubois for suggestion.

**Comment by jandubois** [comment]
I like the name `lima`, so would prefer not to rename the project itself. I think it will be clear from the context if somebody is referring to `lima` the GPU driver, or `lima`, the VM manager. 😄 

I'm partial to using `lima-vm` as the org name, as it keeps the association with the `lima` project name, and makes it clear that is is not about GPUs... You would have a `lima-vm/lima` repo, and if you decide to move it, `lima-vm/vde_vmnet` as well, which looks very descriptive to me.

(I mistyped `lima` as `lime` so many times that I used ![#BFFF00](https://via.placeholder.com/12/BFFF00/000000?text=+) as the color for the `lima` tag in the rancher-desktop repo 😂 )

**Comment by simjnd** [comment]
A lot of organisations revolving around a single project add some sort of extension for the org name (e.g. [preactjs/preact](https://github.com/preactjs/preact), [clap-rs/clap](https://github.com/clap-rs/clap), [darlinghq/darling](https://github.com/darlinghq/darling)) or spell out the domain name they have (e.g. [warpdotdev/warp](https://github.com/warpdotdev/warp) for https://warp.dev, [browsh-org/browsh](https://github.com/browsh-org/browsh) for https://browsh.org). So regardless of the name, whether you keep Lima or not, lima-sh/lima, limash/lima, lima-org/lima, lima-vm/lima, lima-dev/lima and the likes could all be interesting options (maybe with bonus point if there's an available domain name that could be useful later on?).

As for the name of the project itself I personally like the name Lima, and although there's the Lima GPU Driver, I feel like they don't really overlap and that people wouldn't really confuse them (it's not like they're both libs for the same language). I've tried to come up with short, pronounceable two-syllable alternative names that could potentially be considered, and tried to think about the command, org, domain that could go with that:

| Name | Meaning | Command | Control Command | GitHub | Domain Name | Conflicts | Comments |
| - | - | - | - | - | - | - | - |
| Lima | Linux on macOS | `lima` | `limactl` | lima-vm/lima | lima-vm.com | Lima GPU Driver? | Peru's capital |
| Lama | Linux and macOS | `lama` | `lamactl` | lama-vm/lama | lama-vm.com | | The animal could make for a great mascot |
| Mali | macOS and Linux | `mali` | `malictl` | mali-sh/mali | mali.sh | Mali GPUs? | |
| Malin | macOS and Linux | `ml`/`malin` | `mlctl`/`malinctl` | malinsh/malin | malin.sh | | French word for "Smart" |
| Dali | Darwin and Linux | `dali` | `dalictl` | dali-sh/dali | dali.sh | NVIDIA's GPU-accelerated lib for Deep Learning | Salvador Dali |
| Dalin | Darwin and Linux | `dln`/`dalin` | `dlnctl`/`dalinctl` | dalin-sh/dalin | dalin.sh | ? | |
| Darli | Darwin and Linux | `drl`/`darli` | `drlctl`/`darlictl` | darli-sh/darli | darli.sh | ? | |
| Lada | Linux and Darwin | `lada` | `ladactl` | lada-sh/lada | lada.sh | | Russian car brand, cheap but very reliable |
| Lida | Linux on Darwin | `lida` | `lidactl` | lidadotsh/lida | lida.sh | |  |
| Linda | Linux on Darwin | `linda` | `lindactl` | lindash/linda, lindadotsh/linda | linda.sh | | Spanish word for "Pretty", "Beautiful" |

This is the result of a quick brainstorm. Something to keep in mind is that there is the Darling project ([darlinghq/darling](https://github.com/darlinghq/darling)) that allows you to run macOS apps in Linux.

**Comment by jandubois** [comment]
Quick comment on "lama": (in English) that "is a title for a teacher of the Dharma in Tibetan Buddhism". The animal is spelled "llama", and for me that has always been associated with the O'Reilly Llama book (Learning Perl).

Since I prefer to keep the name "Lima" I don't want to press on this too much, but Lima is actually not restricted to running Linux on Mac; it supports running Linux on Linux as well. And while I don't think there is any point in running `qemu` on Windows (you already have WSL), I think there may be a role for using the lima guest and hostagents with WSL2.

So *if* there is a name change, it doesn't have to be restricted to some combination of Linux and macOS, but could use any virtualization related name. My vote is still for `lima` though (not sure if there is voting though 😄 ).

**Comment by simjnd** [comment]
Yeah I knew it wasn't the right spelling but figured that if it was going to be the name, might be fun to play on the fact that they're homophonous 😄. My personal preference is also to keep Lima.

It may go a little be off-topic but just so I understand: is there a point/use-case for using Lima on Linux? Or is it just that it's possible but no one is ever going to use it that way? (kind of like Homebrew exists for Linux but practically no one really uses it)
The description of the repo is "Linux virtual machines, on macOS (aka Linux-on-Mac, macOS subsystem for Linux, containerd for Mac, unofficially)". It may be a little bit outdated already (you can go without containerd for instance). Does Lima now simply mean Linux Machines instead of having ties to macOS? (@AkihiroSuda wanted to call the org linuxmachines)

I'm just wondering because I was working on a logo proposal for the project and the actual meaning is important for that

**Comment by jandubois** [comment]
> is there a point/use-case for using Lima on Linux?

I think so (isolation), but it is not as strong as the macOS use case. But let's say you want to create a local kubernetes cluster with multiple worker nodes, then Lima would be very helpful, as you cannot directly run multiple kubelets on the same host.

As for `linuxmachines`, that is certainly correct right now, but I wonder if it will eventually be possible to run Windows VMs with Windows containers on `qemu` too. Maybe it won't, but that's why I prefer to think of `lima` as a VM manager, like an opinionated higher level abstraction than qemu itself.

**Comment by simjnd** [comment]
I see yeah that makes a lot of sense, thank you!

**Comment by ericem** [comment]
> is there a point/use-case for using Lima on Linux?

This is the exact use case I was searching for a solution when I found Lima. I would like a dependency free tool for launching test VMs (like Vagrant, but without the Ruby baggage). I know Vagrant is being rewritten in Go, but it could be awhile before 3.0 is ready and there is no official qemu/libvirt driver. If I could find Go replacements for Vagrant/Virtualbox and Kitchen/Inspec, I would be in heaven. Bonus points for working on both macOS and Linux. Lima seems like it's headed in the right direction.

**Comment by AkihiroSuda** [comment]
> As for linuxmachines, that is certainly correct right now, but I wonder if it will eventually be possible to run Windows VMs with Windows containers on qemu too. Maybe it won't, but that's why I prefer to think of lima as a VM manager, like an opinionated higher level abstraction than qemu itself.

I wasn't planning to support Windows guests, but I'm happy to accept PRs 😃

**Comment by jandubois** [comment]
> I wasn't planning to support Windows guests, but I'm happy to accept PRs

This is mostly personal curiosity to see if this will be possible at all. I suspect people actually interested in running Windows containers will typically be using Windows laptops/desktops for development too.

Running on a Linux or macOS host will also be impractical because you would need an extra Windows license for the guest VM (I think you need at least Windows Pro to run the Windows version of containerd for development purposes; the hypervisor support in Windows Home is restricted to WSL2).

**Comment by AkihiroSuda** [comment]
I was about to create `github.com/linuxmachines` org but I noticed that `https://github.com/linuxmachine` (without **s**) is already taken, so  `github.com/linuxmachines` might be confusing... 😅

**Comment by simjnd** [comment]
> I was about to create `github.com/linuxmachines` org but I noticed that `https://github.com/linuxmachine` (without **s**) is already taken, so  `github.com/linuxmachines` might be confusing... 😅 

`github.com/linux-machines` looks available, I think adding that dash makes it visually different enough (plus a quick look at the README can let people know they're at the wrong place?)

**Comment by jandubois** [comment]
> `https://github.com/linuxmachine` (without **s**) is already taken

It is a user that has been created more than 2½ years ago, and hasn't been touched since it was registered:

```console
$ gh api /users/linuxmachine | jq -r .created_at,.updated_at
2018-12-01T20:17:44Z
2018-12-01T20:17:44Z
```

I suspect whoever created it has probably lost the credentials for it by now, so I think it makes little difference if this shows an empty user page, or a Github 404 page... 😄 

So I wouldn't worry about it too much. On the other hand, `lima-vm` is still available and maybe less confusing. 😆
