### ISSUE TITLE
Extend the default subuid range from 64k to 1G

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1227]
For:
- https://github.com/runfinch/finch/issues/80

**Comment by ningziwen** [comment]
If the subuid range is limited, no matter how large it is, there can be an image that exceeds it.

I think we may want to think several questions before changing the default value:
1. Is it really necessary to keep the uid/gid that large in the extramely large uid/gid use cases?
2. If yes for 1, how common are the extremely large uid/gid use cases? If it is rare, does it make more sense to make it configurable instead of changing the default value?
3. What is the side effect of making subuid range large?
(unless you know better ones)

**Comment by AkihiroSuda** [comment]
> 1. Is it really necessary to keep the uid/gid that large in the extramely large uid/gid use cases?

Yes, because users can't change the UIDs used in the image without modifying Dockerfile and rebuilding it.
Conceptually we could just hook syscalls to fake UIDs (https://github.com/rootless-containers/subuidless) but it is not matured.

> 2. If yes for 1, how common are the extremely large uid/gid use cases? If it is rare, does it make more sense to make it configurable instead of changing the default value?

Probably rare, and the user can just modify the uid range with `vi /etc/subuid /etc/subgid`.

> 3. What is the side effect of making subuid range large?
>    (unless you know better ones)

It will become hard to allocate subuids without conflicting with other primary users on multi-user env, but it is unlikely to be a problem for Lima.
