### ISSUE TITLE
Allow changing the location of the lima cache

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#1427]
### Description

Currently you can easily change the location of the lima files, using $LIMA_HOME...

It would be nice if it is was just as simple to change the cache location, $LIMA_CACHE.

Both default to using $HOME directories by default, which might not always be suitable.

Should also document the default location on Linux, which is under $XDG_CACHE_HOME.

#### Related

* https://pkg.go.dev/os#UserCacheDir
* https://pkg.go.dev/os#UserHomeDir
* https://pkg.go.dev/os#UserConfigDir

**Comment by jandubois** [comment]
I might prefer to say `$LIMA_HOME/_cache` should replace the default OS cache location (only if it already exists), and then the user can create a symlink to a directory anywhere else if they want to.

This would have the advantage that you only need to specify `LIMA_HOME` and not multiple environment variables. Because if you ever run in a shell that doesn't set `LIMA_CACHE` you would accidentally use the default location again.

I have no strong preferences, but just wanted to mention this for consideration.

**Comment by jandubois** [comment]
> That would require a custom wrapper or setup script to create it, and not just setting environment variables.

How so? All it requires is to run this once:

```
ln -s /Volumes/ThunderBlade/Lima ~/.lima/_cache
```

**Comment by afbjorklund** [comment]
Before starting to use Lima, that was.

**Comment by jandubois** [comment]
> Before starting to use Lima, that was.

You could do it any time afterwards too:

```
mv ~/Library/Caches/lima /Volumes/ThunderBlade/Lima
ln -s /Volumes/ThunderBlade/Lima ~/.lima/_cache
```

As I wrote before, I don't have strong preferences either way, but I generally prefer to not have lots of environment settings for one application. At some point it becomes preferable to have a config file. I just don't think we are quite there yet.

**Comment by jandubois** [comment]
> But it does open up for sharing the Lima cache (between users), even if that is a separate topic...

I'm not sure this is a good idea, especially for "fallback" images, which could be unexpectedly quite outdated.

Adding files to the cache may have race conditions, and pruning becomes unpredictable because it cannot know which images are still being used by other users.

But if you are willing to ignore this, then creating a symlink to the shared cache will work just as well to.

The difference really boils down to:

* environment variable: has to be set every time you invoke `limactl start`
* symlink: is set up once and is linked to `LIMA_HOME`[^1], so switching the home switches the cache as well

[^1]: you can of course link multiple `LIMA_HOME` locations to the same cache, with the same caveats as sharing a cache between users.

**Comment by AkihiroSuda** [comment]
> I might prefer to say `$LIMA_HOME/_cache` should replace the default OS cache location (only if it already exists), and then the user can create a symlink to a directory anywhere else if they want to.
> 
> This would have the advantage that you only need to specify `LIMA_HOME` and not multiple environment variables. Because if you ever run in a shell that doesn't set `LIMA_CACHE` you would accidentally use the default location again.
> 
> I have no strong preferences, but just wanted to mention this for consideration.

SGTM

**Comment by afbjorklund** [comment]
> Adding files to the cache may have race conditions, and pruning becomes unpredictable because it cannot know which images are still being used by other users.

Usually this is solved by making the cache read-only for the users, as far as I know the images are copied before taken in use so the cache images can always be removed ?

**Comment by afbjorklund** [comment]
I think moving the cache directory into the home directory is a different change, and not the one I wanted to do...

It would be possible to symlink also the current location, even if it requires access to the regular cache location first.

**Comment by afbjorklund** [comment]
> * environment variable: has to be set every time you invoke `limactl start`

actually it is only set up for each environment, normally sourced by shell

**Comment by jandubois** [comment]
> actually it is only set up once for each environment, normally sourced by shell configuration

I guess we must be thinking of different user-cases; you seem to expect only a single installation of Lima per environment, and you want to globally adjust the location of the cache.

My starting point (and why I originally introduced `LIMA_HOME`) comes from the desire to have multiple installations of Lima in the same environment, and they should be completely separate from each other.

Originally this was for Rancher Desktop, but now also for finch, and potentially in the future also for colima, when it starts bundling a specific version of Lima (I don't know if the plan is to use a separate `LIMA_HOME` as well).

So with this setup you can install potentially incompatible versions of Rancher Desktop and Lima in any order, update, and uninstall them, and they will be completely ignorant of each other.

Now Rancher Desktop does not make use of the Lima cache (it bundles the ISO, and nerdctl), so I haven't thought about the shared cache situation.

But I can see now that if a "Lima-embedding application" uses the cache, it may not want to be affected when the user has a separate Lima installation and runs `limactl purge`. Which means having a separate cache location could be useful.

So with this use-case in mind, `LIMA_HOME` and the cache location are linked; you wouldn't change one without the other, so having the change happen automatically would be simpler and prevent user errors. Which is why I suggested `$LIMA_HOME/_cache` as an option, to allow an app to isolate.

If you are only concerned about a single `LIMA_HOME` per environment, then I think a symlink in the default cache location already provides the flexibility you need. Just like you don't really need to set `LIMA_HOME`, you could just create a symlink from `~/.lima`.

**Comment by afbjorklund** [comment]
You are right, I wasn't thinking of the forks. And the symlink workaround could take care of the hardcoded cache dir.
