### ISSUE TITLE
Set instance name while starting

### ISSUE THREAD

**Issue by beriberikix** [lima-vm/lima#158]
Running `limactl start foo.yml` automatically sets the instance name to `foo`. It would be nice to be able to set a name different than the file name. Ex. running `limactl start foo.yml --name bar` would create an instance named `bar`.

**Comment by pshail** [comment]
Probably one of the other KEY to override when using the same YAML to spin other VM would be SSH port, I know that muddles the context of this issue but this name override feature won't be usable till that is addressed too IMO

**Comment by jandubois** [comment]
I still feel very strongly that the instance name does not belong in `lima.yaml`, and is different from all the other settings. It serves no purpose in there, as you can only access it if you already know the instance name. Just like you don't store the name of the file inside the file, or the name of a database table inside the table. It would just be redundant information that can get out of sync with reality.

That said, I am very interested in having `--set` supported, especially if it can be used to change settings on an existing instance (like the cpu and memory settings). We discussed some of this before in #131.  I was planning to look into the `helm` code that implements their `--set` command, but I think it was not a good fit, as their `values.yaml` doesn't have any kind of schema.

**Comment by AkihiroSuda** [comment]
We can have `--name NAME` and revisit `--set KEY=VAL` later.

**Comment by jandubois** [comment]
> Also, while we should deprecate `limactl start NEW_INSTANCE_NAME`, we should keep `limactl start EXISTING_INSTANCE_NAME` permanently.

Yes, that's essentially what I suggested, except I want `limactl start NEW_INSTANCE_NAME` to throw an error, so I can recall the command and append `--from-default` or `--from URL`.

I have further suggestions to refine the `--from` argument, but I don't want to complicate the discussion about the basic syntax just yet. 😄 

> Maybe `--set-name` to clarify that this flag is only for new instances?

I find it inconsistent that for new instances the URL is the required argument, but for existing ones it is the NAME. I think it should always be the same. Otherwise it should be a different command `limactl create URL --set-name NAME`. But I still prefer `limactl start NAME --from URL|FILE`.

Of course `--from` (and `--from-default`) will throw an error if the instance already exists.

Again, if `--from` doesn't work for you, then maybe `--template` or `--config` is better, although personally I've now grown fond of `--from`.

<hr>

Ok, I'm still going to mention it: there are 2 additional template locations I would like to see supported:

* `lima.yaml` of existing instances
* examples stored in `/usr/local/share/doc/lima/examples`

So I think `limactl start foo --from bar` should use `$LIMA_HOME/bar/lima.yaml` as the template.

I don't have a suggestion yet how to create a shortcut syntax for the examples folder that is not ambiguous with any of our existing URL/file schemes. We could invent a fake URL prefix, but I don't like that either.

**Comment by AkihiroSuda** [comment]
> I find it inconsistent that for new instances the URL is the required argument, but for existing ones it is the NAME. I think it should always be the same. Otherwise it should be a different command `limactl create URL --set-name NAME`. But I still prefer `limactl start NAME --from URL|FILE`.

We already `limactl start FILE` and I assume we want to keep it, so I think we can just extend it to support `limactl start URL`



> So I think `limactl start foo --from bar` should use `$LIMA_HOME/bar/lima.yaml` as the template.

I'd prefer to have "copy-instance" command for that.
`limactl copy-instance --refresh-disk=(true|false) PARENT CHILD`

**Comment by werediver** [comment]
Renaming existing machines would also be useful. As far as I can tell, there currently is no way to do that (not even `mv ~/.lima/machine1 ~/.lima/machine2`, that breaks the machine). Should renaming be tracked in a separate ticket?

**Comment by AkihiroSuda** [comment]
Yes, renaming is a separate feature

**Comment by AkihiroSuda** [comment]
Implemented in https://github.com/lima-vm/lima/pull/674
