### ISSUE TITLE
CI: test WSL2

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1781]
Follow-up to:
- https://github.com/lima-vm/lima/pull/1721

`runs-on: windows-2022-8-cores` ([larger runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners)) is known to support Hyper-V, but not sure if it supports WSL2.
Probably it should work: https://techcommunity.microsoft.com/t5/itops-talk-blog/wsl2-now-available-on-windows-server-2022/ba-p/3447570

**Comment by pendo324** [comment]
I can't find the documentation about `windows-2022-8-cores` on the GitHub larger runner page, but as long as it supports virtualization, WSL2 should work.

We're planning on using a Windows Server runner to test Finch's usage of this feature as well (the [work-in-progress PR is here](https://github.com/runfinch/infrastructure/pull/411) if you're interested in the entire process, but what's more interesting is probably the [PowerShell script we're planning to run](https://github.com/runfinch/infrastructure/pull/411/files#diff-a58551a61497fe5ea88dbff2e511e136c7fd1dee2b71a0aa51a1eb057fe75e86)). For some details on how we're planning on doing it:

1. Install [WinGet](https://github.com/microsoft/winget-cli), and use it to install the other dependencies required to run Lima on Windows, but its not 100% necessary. Technically, you can just install via MSIs
    1. Unfortunately, this is not so simple on Windows Server right now, but it does come pre-installed with all other (modern) editions of Windows
    1. If this comes preinstalled on the GitHub provided runners, that would simplify things considerably
1. Install Git for Windows (provides `git.exe`, `ssh.exe`, `cygpath.exe`, `tar.exe`, `gzip.exe`, `make.exe` and more). Finch will do this via WinGet. Only the MinGit release is required
    1. Example winget command: `winget install -e --id Git.MinGit`
1. Install go. The most supported way seems to be by using the MSI installer directly.
    1. Example of installing go: `Invoke-WebRequest -Uri 'https://go.dev/dl/go1.21.0.windows-amd64.msi' -OutFile 'go1.21.0.windows-amd64.msi'; Start-Process msiexec.exe -Wait -ArgumentList '/I C:\Users\Administrator\setup\go1.21.0.windows-amd64.msi /quiet'`
1. Enable WSL2 (requires restart)
    1. `wsl --install`

From here, the runner should be setup, and the remaining steps should be very similar to how the CI is run on macOS/Linux (clone repo, make, run tests), with the key difference being specifying the usage of the experimental `wsl2.yaml`.

I guess a maintainer would have to add the runner to this repo in order to test anything right?

**Comment by AkihiroSuda** [comment]
> windows-2022-8-cores

Added by myself. This is a “larger” runner managed by GitHub.
https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners
