### ISSUE TITLE
`template://podman-rootful`: provision scripts should not depend on `LIMA_CIDATA_*`

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#2055]
https://github.com/lima-vm/lima/blob/b453dedb757e5fc1e249f352d0812d008e66fa3f/examples/podman-rootful.yaml#L44

The provision scripts should probably use template like `{{.User}}`
https://github.com/lima-vm/lima/pull/2052#issuecomment-1839114367

**Comment by afbjorklund** [comment]
Also used in docker-rootful, I think

**Comment by jandubois** [comment]
@AkihiroSuda Can you explain why template variables are preferable to the env variables?

It makes no big difference, but env variables are slightly more flexible if you want to work on the scripts in a running instance because the variables are not yet filled in (you can make changes to the script and copy it back into `lima.yaml`).

Another thing is that `lima.env` can be used to look up what information is available. But I guess we can document all the template variables in `default.yaml` as well.

Anyways, no strong feelings either way.

**Comment by AkihiroSuda** [comment]
> Can you explain why template variables are preferable to the env variables?

Because these variables are implementation details of the init scripts, and can be removed even in a patch release.

**Comment by jandubois** [comment]
> Because these variables are implementation details of the init scripts, and can be removed even in a patch release.

Oh, so the template would only make a subset of the information available? I thought you wanted to apply the cidata templating function to the scripts, which is functionally equivalent to exposing the shell variables; `lima.env` is essentially the mapping function.

So what are the template variables that should be exposed via the template?

**Comment by AkihiroSuda** [comment]
> So what are the template variables that should be exposed via the template?

Just same as the template for the sockets?
https://github.com/lima-vm/lima/blob/b453dedb757e5fc1e249f352d0812d008e66fa3f/examples/default.yaml#L364

**Comment by jandubois** [comment]
> Just same as the template for the sockets?

Ok, that works for me.

Would the `LIMA_*` variables still remain available for the system provisioning scripts (for backwards compatibility), or would you want to block them?

I guess we could do a string match for `LIMA_CIDATA` on the expanded script template and generate a warning?

**Comment by AkihiroSuda** [comment]
> I guess we could do a string match for LIMA_CIDATA on the expanded script template and generate a warning?

👍
