### ISSUE TITLE
vz mode now prints `WARN[0001] vmType vz: ignoring [TimeZone] ` on every start up

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#2105]
>  vz mode now prints `WARN[0001] vmType vz: ignoring [TimeZone] ` on every start up

_Originally posted by @AkihiroSuda in https://github.com/lima-vm/lima/issues/2097#issuecomment-1872671273_

**Comment by jandubois** [comment]
I've created #2106 with the obvious fix, but I feel like this `knownYamlProperties` mechanism is not the right way to deal with these things.

Especially since this is a lie: the VZ driver knows nothing about this property at all; it is just something passed through to cloud-init and doesn't need any driver support.

It is not super important, but this should probably be refactored somehow into the `limayaml` package, and maybe only properties requiring additional driver support should be marked up especially.
