### ISSUE TITLE
Make setting AcceptEnv more robust

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#2207]
> [the way we're adding COLORTERM to the sshd's AcceptEnv](https://github.com/lima-vm/lima/blob/88c89165273d87b33753a593af867b20c1d1c67d/pkg/cidata/cidata.TEMPLATE.d/boot/11-colorterm-environment.sh#L15) is broken on some modern distro's (like Fedora) because they don't ship an /etc/ssh/sshd_config with AcceptEnv in it at all.

_originally posted by @pendo324 in #2202_

I would suggest to write the AcceptEnv to a file in /etc/ssh/sshd_config.d when possible, and only patch /etc/ssh/sshd_config as a backup when the directory doesn't exist (see https://github.com/lima-vm/lima/pull/2202#issuecomment-1946708624).

**Comment by afbjorklund** [comment]
We don't actually use COLORTERM outside the "default" template, and Fedora doesn't do colors anyway...

But I suppose that theoretically some user could be wanting "truecolor" support for their custom shell?

**Comment by afbjorklund** [comment]
Nice timing! https://fedoraproject.org/wiki/Changes/Color_Bash_Prompt says it was added in fc39

![](https://petersen.fedorapeople.org/color-bash-prompt.png)

**Comment by afbjorklund** [comment]
Regarding the Fedora colors above, they only support 256 colors so truecolor doesn't really matter...

Or I suppose technically they support _any_ color, since the parameter only specifies the "ANSI codes"

But if you want the lima color, you can do:

`export PROMPT_COLOR="38;2;50;205;50"`

To get the OS color, there is a command:

`prompt_default_os` # reads /etc/os-release

* `#3C6EB4` "Fedora Blue"

* https://fedoraproject.org/wiki/Logo/UsageGuidelines#Colors

----

But the default color in Fedora is green (32), similar to ubuntu's green bold (1;32)

![lima-fedora-color-prompt](https://github.com/lima-vm/lima/assets/10364051/d0a55f39-81e4-4d99-b6e8-48946edaa18c)
