### ISSUE TITLE
Intel Mac Cannot run "arch=aarch64"

### ISSUE THREAD

**Issue by bobhenkel** [lima-vm/lima#269]
There was an older issue on this that is currently closed. I put my details as a comment to that.

https://github.com/lima-vm/lima/issues/19

Thanks!

**Comment by jandubois** [comment]
This is a different issue that #19. Your problem is that your `ubuntu.yaml` does not specify the architecture, so it will default to the host arch (`x86_64`), but you don't provide a URL to download the OS image.

Add this line to your `ubuntu.yaml`:

```yaml
arch: aarch64
```

It is starting for me, but I don't have the patience to wait until the VM is running.

You may also want to add:

```yaml
video:
  display: cocoa
```

to get a console Window, so you have something to use for debugging if it doesn't come up. The last time I tried this, it took 30min to just boot the VM.

Hmm, it seems a little faster this time:

```
INFO[0031] SSH Local Port: 60028
INFO[0031] [hostagent] Waiting for the essential requirement 1 of 4: "ssh"
INFO[0116] [hostagent] Waiting for the essential requirement 1 of 4: "ssh"
INFO[0144] [hostagent] Waiting for the essential requirement 1 of 4: "ssh"
INFO[0154] [hostagent] Waiting for the essential requirement 1 of 4: "ssh"
INFO[0164] [hostagent] Waiting for the essential requirement 1 of 4: "ssh"
INFO[0175] [hostagent] Waiting for the essential requirement 1 of 4: "ssh"
INFO[0206] [hostagent] The essential requirement 1 of 4 is satisfied
INFO[0206] [hostagent] Waiting for the essential requirement 2 of 4: "sshfs binary to be installed"
INFO[0247] [hostagent] Waiting for the essential requirement 2 of 4: "sshfs binary to be installed"
INFO[0287] [hostagent] Waiting for the essential requirement 2 of 4: "sshfs binary to be installed"
INFO[0328] [hostagent] Waiting for the essential requirement 2 of 4: "sshfs binary to be installed"
```

I may leave it running for a while longer, just to see if it still works, but the fans are now running full blast...

**Comment by jandubois** [comment]
Closing this now, as I've shown that you can run `arch=aarch64` on Intel Mac. Feel free to re-open (this issue, not #19), if you still have problems!
