### ISSUE TITLE
DNS native host resolving no longer works with vz VMs since v1.0.0

### ISSUE THREAD

**Issue by dhealio** [lima-vm/lima#2939]
### Description

When using the `vz` VM and not using user-v2 networking, the DNS behavior mentioned in the [documentation](https://lima-vm.io/docs/config/network/#dns-19216853) is no longer working as advertised when `hostResolver.enabled` is true (or unassigned).

This prevents being able to use the native OS resolver, which is needed for VPN configurations, split-DNS setups, as well as mDNS, local /etc/hosts etc.

The breaking change seems to be [here](https://github.com/lima-vm/lima/pull/1626/files#diff-6a911aa7574099e18369e9477b214a031077350dedc30e60b933ad0f61e022c2R259), which prevents `args.UDPDNSLocalPort` etc. from getting assigned.

**Comment by nirs** [comment]
Based on the comment this a regression.

**Comment by balajiv113** [comment]
@dhealio 
The reason for that condition is, vz uses gvisor implementation for network. For that dns resolution is taken care by gvisor-tap-vsock. Which will take care of reading /etc/hosts to populate nameservers

The change in behaviour is due to gvisor-tap-vsock breaking change. This is fixed later. So after upgrade gvisor-tap-vsock it should work fine. Will check with gvisor-tap-vsock for a release
https://github.com/containers/gvisor-tap-vsock/issues/398

**Comment by subpop** [comment]
Using v1.0.2 as well. When I start up my `default` guest, this gets printed:

```
INFO[0010] [hostagent] Not forwarding TCP 127.0.0.53:53
```

That's the address that ends up in `/etc/resolv.conf` in the guest. Is that relevant?

**Comment by jandubois** [comment]
`127.0.0.53:53` is the address for `systemd-resolved`, which will be running inside the VM.

You can run `resolvectl status` inside the VM to see what it is using to resolve names.

**Comment by nirs** [comment]
Should we reopen this issue or open a new one?

**Comment by subpop** [comment]
I've been experimenting with a guest and my hostagent resolver. When the hostagent starts, it successfully starts up the DNS resolver and listens on a random port (in this example, 50563). From my Mac, querying the resolver directly works for both VPN and non-VPN hosts:

```
dig @127.0.0.1 -p 50563 google.com
```

I can see the `handleQuery received DNS query` log entry when this happens. From within a guest, I can also succeed in querying the resolver if I dig at that port.

I modified the cloud-init generated systemd.network file (`/run/systemd/network/10-netplan-eth0.network`) and set the `DNS=` entry to `192.168.5.2:50563` (instead of just the IP address) and restarted systemd-networkd. After that, `resolvectl query` will successfully resolve VPN hosts and non-VPN hosts, and I can see handleQuery log entries.

So it appears that the hostagent resolver is working, but something is misconfigured with the ports so that the resolver is not listening on a port that the guest is querying.

**Comment by subpop** [comment]
I don't know if it's a true workaround, but I was able to get my VPN hostnames resolving in a guest by creating a guest using:

```
networks:
- vzNAT: true
vmType: vz
```

This seems functional enough for my needs.

**Comment by subpop** [comment]
In a Fedora guest using systemd-networkd and systems-resolved, I have not had any issues. On guests running NetworkManager (like CentOS), I had to manually set the `ipv4.dns-priority` value of the `lima0` interface to a number higher than 0 so that it would be listed earlier in the generated `/etc/resolv.conf`. I did this by adding a connection override in `/etc/NetworkManager/conf.d/dnf.conf`:

```
[connection-cloud-init-lima0]
match-device=interface-name:lima0
ipv4.dns-priority=50
```

**Comment by nirs** [comment]
> On guests running NetworkManager (like CentOS)

Does this apply to Ubuntu 24.04?

**Comment by subpop** [comment]
> > On guests running NetworkManager (like CentOS)
> 
> Does this apply to Ubuntu 24.04?

I just created a 24.04 guest and it appears to be using systemd-networkd/systemd-resolved like my Fedora guest. As long as it's created with `--network vzNAT` and has both an `eth0` and a `lima0` Ethernet interface, both VPN and non-VPN domains resolve correctly. No additional configuration changes are required. I didn't even need to restart any services. I started the guest and then after it was up, connected to VPN. After connecting to VPN, the VPN domains started resolving within the guest after a second or two of uptime.
