### ISSUE TITLE
when I run "limactl start --debug" in my mac 10.14.6, it cannot startup and show some message, how can i do? (`failed to run [system_profiler SPNetworkDataType -json]`)

### ISSUE THREAD

**Issue by pengtaoman** [lima-vm/lima#350]
limactl start --debug

DEBU[0000] interpreting argument "default" as an instance name "default"
INFO[0000] Using the existing instance "default"
DEBU[0000] Make sure "shared" network is stopped
DEBU[0000] Make sure "bridged" network is stopped
DEBU[0000] Make sure "host" network is stopped
INFO[0000] [hostagent] time="2021-10-19T16:53:34+08:00" level=fatal msg="failed to run [system_profiler SPNetworkDataType -json]: stdout=\"\", stderr=\"Usage: system_profiler [-listDataTypes]\\n       system_profiler [-xml] [-timeout n] [-detailLevel n]\\n       system_profiler [-xml] [-timeout n] [dataType1 ... dataTypeN]\\n\\n  -detailLevel n    specifies the level of detail for the report\\n                      mini = short report (contains no identifying or personal information)\\n                      basic = basic hardware and network information\\n                      full = all available information\\n\\n  -listDataTypes    lists all the available datatypes\\n\\n  -xml              generates xml output instead of plain text\\n                    if redirected to a file with the extension \\\".spx\\\"\\n                    the file can be opened in System Profiler.app\\n\\n  -timeout          specifies the maximum time to spend gathering information\\n                    the default is 180 seconds, 0 means no timeout\\n\\n  Redirect stderr to /dev/null to suppress progress and error messages.\\n\\nExamples:\\n\\n  system_profiler\\n     Generates a text report with the standard detail level.\\n\\n  system_profiler -detailLevel mini\\n     Generates a short report without identifying/personal information.\\n\\n  system_profiler -listDataTypes\\n     Shows a list of the available data types.\\n\\n  system_profiler SPSoftwareDataType SPNetworkDataType\\n     Generates a text report containing only software and network data.\\n\\n  system_profiler -xml >MySystem.spx\\n     Creates a XML file which can be opened by System Profiler.app\\n\\n\": exit status 1"
FATA[0000] host agent process has exited: exit status 1

**Comment by AkihiroSuda** [comment]
Probably you need to use macOS 10.15 or later

cc @jandubois

**Comment by AkihiroSuda** [comment]
Setting `useHostResolver: false` may work as a workaround

https://github.com/lima-vm/lima/blob/5237bfef3f1eec5caeb944ff769de3bc3db89a23/pkg/limayaml/default.yaml#L197

**Comment by jandubois** [comment]
> Probably you need to use macOS 10.15 or later

Likely. I don't have an OS X 10.14 VM available right now, but on 10.12.6 I can see that `system_profiler` does not yet support the `-json` option, so it is probably a reasonable assumption that this was only added in 10.15.

> Setting `useHostResolver: false` may work as a workaround

I don't think that is going to work because the code to fetch the system proxy settings also uses the `system_profiler` data.

Also, we only need to read the system DNS settings when we are **not** using the host resolver. If we are using the host resolver, then the only configured DNS in the guest is the slirp one.

Not sure what we should do about it; I don't really want to switch to parsing XML.

I would suggest that we check the mac OS version number and will not attempt to read system proxy settings on releases before 10.15. Users can still set the variables themselves using the `env` key in `lima.yaml`, or via environment variables when invoking `lima start`.

I would also suggest that we document that 10.15 is the oldest "fully supported" version of OS X. 10.14.6 hasn't been updated by Apple in over 2 years, and there are now 3 newer versions available: 10.15, 11, and 12.

We'll try to support older releases on "best efforts", but possibly with limited functionality?
