### ISSUE TITLE
Provide a way to pass in the wait timeout for emulation mode

### ISSUE THREAD

**Issue by gayanper** [lima-vm/lima#418]
Since the emulation mode like arm on intel or intel on arm will take a lot of time to create the vm, it would be nice to pass in the timeout. The default could be 10min as it is now. But in emulation mode one could override it by passing in as a parameter for both start and stop commands.

**Comment by antoineco** [comment]
This configuration flag / instance option is very much needed IMO, with or without emulation mode.

RIght now on slow hosts such as GitHub Actions' macOS runners (_which come with Lima pre-installed, by the way_) I am not even able to complete the installation of `kernel-devel` OS packages, which require a lot of resources due to post-install scripts generating the `initramfs` using `dracut`.

https://github.com/lima-vm/lima/blob/082576f99cb4fbb3844b69df21c2e13c65bd58be/pkg/start/start.go#L188

A solution I would consider ideal would be to add a `timeout` parameter to `provision` steps. I think that approach would allow config authors to communicate clearly that a certain provisionning step is expected to take a long time, and `limactl start` could naively consider the sum of those values + its own default.

Another approach would be to set that timeout on `probes`, for the same result as described above.

**Comment by jandubois** [comment]
I think I prefer the original suggestion of making the global timeout configurable. This should be fairly simple to implement and document as well.

I think the timeout mostly depends on the host, so putting host-specific timeouts into the template feels wrong.

If you want to have specific (shorter) timeouts in your provisioning scripts, you can already do this by putting the script into a function and calling it via the `timeout` command.

**Comment by antoineco** [comment]
> putting host-specific timeouts into the template feels wrong.

That's a valid point, I didn't consider that carefully enough in my previous comment.

I'll send a PR as a proposal for implementing a start-global `timeout` flag.
