### ISSUE TITLE
provide another flag to give better understanding about alternative examples in lima

### ISSUE THREAD

**Issue by developer-guy** [lima-vm/lima#589]
Once you first start using lima, you might not understand what you can achieve by using lima in the first place. To make understanding better, we have some mentions of examples/ folder in several places in documents. But what if we provide an alternative command to list all the examples in the first place and let people select one of them to continue with it? @dentrax

```shell
$ limactl list-supported-engines # will show us the examples within the examples/ folder
docker
podman
k3s
k8s
...

$ limactl start <instance_name> --engine <docker> # to select one of the engine we provide
```

WDYT?

**Comment by jandubois** [comment]
We had a lengthy discussion about something related in #158. Unfortunately we left this dangling, and nothing got implemented.

I think I'm still partial to my suggestion in https://github.com/lima-vm/lima/issues/158#issuecomment-947119612, but we didn't reach agreement on it.

As for terminology, I don't want to reference example configurations as "engines". If anything I would call them "templates".

I've been thinking about supporting something like `$LIMA_HOME/_templates` as an additional location to store template configurations that could be referenced with a short name.

If you want to work on this area, I think we'll need to spend more time bike-shedding first to reach consensus of how the different pieces should work together.

**Comment by afbjorklund** [comment]
The use of "engine" here is somewhat confusing, but then so again is the word "runtime".
(being used for both "container runtime" as in e.g. CRI and for "OCI runtime" as in runc)

https://developers.redhat.com/blog/2018/02/22/container-terminology-practical-introduction

I think it can be solved by more documentation about the yaml examples, rather than code ?

Anyway, your list is missing the default (nerdctl), but then adding _orchestrators_ next to it...
The choice of Linux distribution is also somewhat confusing, since it doesn't change much.

Example | Distro | Engine | Rootless | Orchestrator
--- | --- | --- | --- | ---
`alpine.yaml` | alpine | - | no | -
`archlinux.yaml` | arch | nerdctl | yes | -
`debian.yaml` | debian | nerdctl | yes | -
`fedora.yaml` | fedora | nerdctl | yes | -
`opensuse.yaml` | opensuse | nerdctl | yes | -
`rocky.yaml` | rocky | nerdctl | yes | -
`ubuntu.yaml` | ubuntu | nerdctl | yes | -
`docker.yaml` | ubuntu | docker | yes | -
`podman.yaml` | ubuntu | podman | yes | -
`singularity.yaml` | fedora | singularity | yes | -
? |  ubuntu | lxc | yes | lxd
`k3s.yaml` | ubuntu | containerd | no | kubernetes
`k8s.yaml` | ubuntu | containerd | no | kubernetes
`nomad.yaml` | ubuntu | containerd | no | nomad
`faasd.yaml` | ubuntu | containerd | no | openfaas

One _could_ provide more different combinations, like fedora-podman, if really needed.
There is no real practical difference between the nerdctl and "only" containerd, either.

I made some variants with [Fedora](https://github.com/afbjorklund/fedora-lima), but there is no user visible difference. It was just [NIH](https://en.wikipedia.org/wiki/Not_invented_here).

**Comment by afbjorklund** [comment]
There was some suggestions to add descriptions and icons and links, before...

But it doesn't _have_ to be done in the yaml format, it can be done in markdown.

**Comment by jandubois** [comment]
It feels like you are over-engineering things now. I think adding a `description` property to each template, and having a command to list all available templates with their description is fine.

Trying to categorize the templates along multiple dimensions feels like a futile effort: there will always be instances that don't fit into that schema. In the end you can create arbitrary VMs. We ship a list of examples with Lima, both to show users different ways the lima configuration system can be used, and to give people a useful starting point to customize their own.

But if this is turning into a full-blown app-store for virtual appliances, then I think that should probably be a website that is maintained independently of the Lima tool itself. It could still be part of the lima-vm org though, but should be a separate repo and requires some commitment of long-term maintenance. I'm afraid it would suffer the typical fate of a wiki: initially maintained with enthusiasm, but eventually getting out-of-date, full of unmaintained cruft.

So my opinion is to start small, with incremental improvements.

**Comment by afbjorklund** [comment]
I think that is the same conclusion that we came to the last time, and it hasn't really changed since.

**Comment by afbjorklund** [comment]
To be honest, I don't think that Ubuntu is very important here either. It just happens to be well known...

It has its own agenda, with the slapd and the lxd and the other cruft, as well as multipass and microk8s.

But if ever needed, one could do an "ubuntu-lima" and customize it a bit (similar to "alpine-lima" today) ?

**Comment by jandubois** [comment]
FWIW, there are no pre-built public Alpine images with cloud-init, afaik. So there was no choice but to build a custom image.

Generally I think it is not worth it to create custom images for all the distros. We don't want to replicate the AWS maketplace for AMIs. 😄 

What we _may_ want to do eventually is to add support for copying/cloning existing instances. So you could setup and customize your master instance, and then stop it. Any time you need a pristine image, you copy/clone from this master image instead of starting from scratch. Maybe use hardlinks for the original image file (baseDisk), to save some disk space.

This allows much more flexibility in users creating their own template images, without putting the maintenance burden on somebody else.

**Comment by afbjorklund** [comment]
> Generally I think it is not worth it to create custom images for all the distros. We don't want to replicate the AWS maketplace for AMIs. :smile:

I only meant the "default" images.

**Comment by afbjorklund** [comment]
I would avoid the "on Ubuntu" parts.

**Comment by afbjorklund** [comment]
Here is a graphic version, that I was playing with for the GUI:

![lima-gui-quick-start](https://user-images.githubusercontent.com/10364051/151628518-f7cf7e18-9ac4-43d4-8f25-d2ff5396aa5f.png)

The "Advanced..." button would open up the regular YAML editor.

The overrides (or parameters) should probably have popups/sliders.

**Comment by afbjorklund** [comment]
Added a checkbox for dropping into the yaml editor after preloading the template, for changing things:

![quick-start-edit-yaml](https://user-images.githubusercontent.com/10364051/151702971-1b629e1c-1472-4144-82fa-143631b6c0cd.png)

Not sure where the other parameters should actually go, if they should be merged into the YAML file ?

Also how to get those default values, I _could_ hardcode 4 CPUs and 4GiB Memory and 100GiB Disk.

**Comment by AkihiroSuda** [comment]
Implemented in https://github.com/lima-vm/lima/pull/674
