### ISSUE TITLE
Reduce the memory to < 4 GiB, when QEMU >= 7.0 && macOS <= 12.3 && CPU == M1

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#795]
QEMU 7.0 beta is known to cause host kernel panic on M1 (Prox/Max only?) when the guest memory exceeds 4GiB limit, but the host kernel panic is reported to be fixed in macOS 12.4 beta

https://gitlab.com/qemu-project/qemu/-/issues/903#note_911000975

But not all people can upgrade macOS immediately, so probably we should reduce the default memory to 2GiB when QEMU >= 7.0 && macOS <= 12.3 && CPU == M1 .

**Comment by jbreiding** [comment]
Is this still present in qemu 7.0.0 release?

Perhaps there is a better way to detect this state than just the version?

**Comment by jbreiding** [comment]
Okay, upgrading my os the 12.4 seems to have made the error go away.

Apologies

**Comment by bguyza** [comment]
How do I go about downgrading `qemu`?

**Comment by pwillis-eiq** [comment]
Thanks @Amar1729 that Podman issue fix worked for me! However I had to do the following:

```
$ curl -L -H "Authorization: Bearer QQ==" -o qemu-6.2.0_1.monterey.bottle.tar.gz https://ghcr.io/v2/homebrew/core/qemu/blobs/sha256:fcc3b1a8139f70dae57f5449f3856f9b3b67448ee0623e64da1e47dc255b46f6
$ while brew list qemu ; do brew uninstall qemu ; done
$ HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install --ignore-dependencies -f ~/Downloads/qemu-6.2.0_1.monterey.bottle.tar.gz lima
```

Otherwise 1) new versions of qemu would not allow linking the 6.2 version, 2) qemu would auto-upgrade to v7 (the environment variable fixes it), and 3) lima dependencies would auto-upgrade qemu to v7 (`--ignore-dependencies` fixes it).

What a huge pain, just because Homebrew became a nanny state.
