### ISSUE TITLE
Rancher Desktop's limactl invocation doesn't pass through CONTAINERD_ADDRESS envvar

### ISSUE THREAD

**Issue by huyz** [lima-vm/lima#961]
### Description

macOS: 12.4 on MacBook ARM
Rancher Desktop v1.4.1
limactl version 0.9.2-54-ge82db87

I don't know if this is a problem with limactl or with Rancher Desktop's usage of limactl, but I can't seem to set the envvar `CONTAINERD_ADDRESS` so that nerdctl can read it.

```shell
❯ CONTAINERD_ADDRESS=/var/run/docker/containerd/containerd.sock nerdctl container ls
FATA[0000] cannot access containerd socket "/run/k3s/containerd/containerd.sock" (hint: try running with `--address /var/run/docker/containerd/containerd.sock` to connect to Docker-managed containerd): no such file or directory

❯ which nerdctl
/Users/huyz/.rd/bin/nerdctl

❯ cat =nerdctl
#!/bin/bash
set -eu -o pipefail

scriptname="${BASH_SOURCE[0]}"
while [ -L "${scriptname}" ]; do
    scriptname="$(readlink "${scriptname}")"
done
scriptdir="$(cd "$(dirname "${scriptname}")" && pwd)"

if ! LIMA_HOME="$HOME/Library/Application Support/rancher-desktop/lima" "${scriptdir}/../lima/bin/limactl" ls --json | grep '"name":"0"' | grep -q '"status":"Running"'; then
  echo "Rancher Desktop is not running. Please start Rancher Desktop to use nerdctl";
  exit 1
else
  LIMA_HOME="$HOME/Library/Application Support/rancher-desktop/lima" "${scriptdir}/../lima/bin/limactl" shell 0 sudo --preserve-env=CONTAINERD_ADDRESS nerdctl "$@"
fi
```

Looks like `sudo` at least tries to pass `CONTAINERD_ADDRESS` but limactl somehow fails to do its part.

**Comment by jandubois** [comment]
> I don't know if this is a problem with limactl or with Rancher Desktop's usage of limactl, but I can't seem to set the envvar `CONTAINERD_ADDRESS` so that nerdctl can read it.

If this is for Rancher Desktop, then I don't understand why you want to modify the socket address; it is already set to the correct location where RD configures containerd to listen.

This variable is set `~/.profile` inside the VM because that's where `nerdctl` executes; it then just needs to be passed by sudo as well, as we run it as `root`.

If the socket doesn't exist/work, then either something else is wrong inside the VM, or you have configured RD to use `moby` instead of `containerd`. You can only use `nerdctl` with the `containerd` runtime.

Either way, this seems like a RD issue and should be filed in the RD repo, not in the Lima repo.

**Comment by jandubois** [comment]
I just saw you also filed https://github.com/rancher-sandbox/rancher-desktop/discussions/2552, where you confirmed that you are using `dockerd` and not `containerd`. In that case you should use the `docker` cli and not `nerdctl`.
